Jet Test Appliction. Stage 1
a-shpak/jet-start-1 pull request #1
Opened 2021-10-07 19:12 UTC by a-shpak

2021-10-08 06:46 UTC, VeraOrekhXB requested changes

2021-10-08 06:46 UTC, VeraOrekhXB commented on sources/views/contacts/info.js
> +				{view: "label", localId: "skype", label: "Skype", height: h, width: w, css: "label-info", template: setIcon("fa-skype")},
Для отображения иконки скайпа в темплейте должна быть строка fab fa-skype, а у тебя по дефолту всегда приставка fas

2021-10-08 06:46 UTC, VeraOrekhXB commented on sources/views/activities.js
> +					{id: "completed", header: "", template: "{common.checkbox()}", minWidth: 150},
Зачем для колонки, в которой только один чекбокс, минимальная ширина в 150? Колонка получается очень широкая и теряется много полезного места

2021-10-08 06:46 UTC, VeraOrekhXB commented on sources/views/activities.js
> +						header: ["Due date", {content: "textFilter"}],
Здесь должен быть фильтр для выбора даты https://docs.webix.com/datatable__filtering.html#datepicker

2021-10-08 06:46 UTC, VeraOrekhXB commented on sources/views/activities/popup.js
> +			{view: "text", label: "Details", height: 70, name: "details"},
Обычно если указано на макете поле, которое больше других однострочных, то скорее всего это не обычный ui.text с большей высотой, а ui.textarea

2021-10-08 06:46 UTC, VeraOrekhXB commented on index.html
> +	<script type="module" src="/jet-start-1/sources/views/activities/popup.js"></script>
Я рекомендую сделать так:
1.  Не подключать в html этот js файл для попапа
2.  Создать отдельную JetView для него
3.  В JetView activities grid ```this._activityPopup = new ActivityPopup({necessary arguments values for constructor})```
4.  В методе destroy (https://webix.gitbook.io/webix-jet/api/jetview-api/jetview-handlers#destroy) вызвать метод close у окна, а в других случаях hide

2021-10-08 06:46 UTC, VeraOrekhXB commented on sources/models/activities.js
> +const activitiesCollection = new webix.DataCollection({
Вроде бы все данные должны быть подгружены с сервера, а не быть статичными

2021-10-08 06:46 UTC, VeraOrekhXB commented on sources/views/activities.js
> +function showPopup(object, table) {
Эту функцию можно добавить как метод в класс
Либо если ты считаешь, что эта логика должна быть отдельной от данной JetView, тогда выноси в отдельный файл

2021-10-08 06:46 UTC, VeraOrekhXB commented on sources/views/activities.js
> +			contactsCollection.data.each((val) => {
Лучше перенести это в саму дата коллекцию в scheme $init

2021-10-08 06:46 UTC, VeraOrekhXB commented on sources/views/activities/popup.js
> +						const values = webix.$$("popup_form").getValues();
Вместо ```webix.$$("popup_form").getValues()``` используй ```form.getValues()```

2021-10-08 06:46 UTC, VeraOrekhXB commented on sources/views/contacts/info.js
> +function setIcon(icon) {
К похожей ситуации писала коммент выше: либо внутри класса, либо в отдельный файл, который будет импортироваться

2021-10-08 09:43 UTC, kullias commented on sources/views/activities.js
> +function showPopup(object, table) {
jet-style - метод класса все-таки, да

2021-10-08 09:44 UTC, kullias commented on sources/views/contacts/info.js
> +function setIcon(icon) {
но лучше метод класса

2021-10-08 10:04 UTC, kullias commented on index.html
> +	<script type="module" src="/jet-start-1/sources/views/activities/popup.js"></script>
оно еще и ошибку кидает (в консоли 404), когда открываешь на контактах

2021-10-08 10:16 UTC, kullias commented on sources/models/activities.js
> +const activitiesCollection = new webix.DataCollection({
и операции все должны тоже на бэк все сохранять (чекбоксы, редактирование, добавление, удаление)
об этом есть в ТЗ

2021-10-08 12:36 UTC, kullias commented
детали ревью в комментариях, и еще:

1) после операций (добавление, редактирование), если делать их после фильтрации, фильтрация сбивается
- в фильтрах есть значения
- данные не отфильтрованы

это некритично, но если бы это был настоящий проект, выглядело бы как баг

2) backend из клиентского приложения стоит удалить / добавить в игнор и не коммитить, он у нас отдельно

2021-10-08 12:36 UTC, kullias requested changes

2021-10-08 12:36 UTC, kullias commented on sources/views/activities.js
> +				icon: "fa-plus-square",
иконки не видно

2021-10-08 12:36 UTC, kullias commented on sources/myapp.js
> +		app.attachEvent("app:error:resolve", () => webix.delay(() => app.show("/top/contacts")));
❤️

2021-10-08 12:36 UTC, kullias commented on sources/views/top.js
>  		let header = {
если какую-то переменную используем как константу, пусть она и будет константой

2021-10-08 12:36 UTC, kullias commented on sources/views/top.js
> +				{value: "Settings", id: "settings", icon: "fa fa-cog"}
у меня иконка какая-то другая отрисовывается (пустой квадрат)

2021-10-08 12:36 UTC, kullias commented on sources/views/contacts.js
> +				list,
его можно просто статически включить, просто ContactsListView
конструкторы мы определяем и передаем туда какие-то параметры обычно если нам надо по одному классу создавать однотипные, но чем-то отличающиеся вьюшки

2021-10-08 12:36 UTC, kullias commented on sources/views/contacts.js
> +		const info = new ContactInfoView(this.app, 0);
_contactId нигде не используется, айди хранятся в параметре урла. нужен ли нам этот параметр в конструктор и нужен ли сам кастомный конструктор?
нет

2021-10-08 12:36 UTC, kullias commented on sources/views/contacts/list.js
> +					this.$scope.show(`/top/contacts?id=${id}`);
тут проще функцию-стрелку использовать и не использовать $scope
к скоупу и простой функции мы прибегаем от безысходности, когда нам надо this-виджет, а не (или не только) this-вьюшка

2021-10-08 12:36 UTC, kullias commented on sources/views/contacts/info.js
> +					text: `Contact is not founded, id:${id}`
not found

2021-10-08 12:36 UTC, kullias commented on sources/views/contacts/info.js
> +	showContact(contact) {
интересное решение
чисто по коду можно сделать короче, если все это будет в форме (top layout), у каждого лейбла будет name и потом просто можно будет вызывать form.setValues(...)

2021-10-08 12:36 UTC, kullias commented on sources/views/activities.js
> +						activitiesCollection.updateItem(id, item);
не надо
ты даже тут можешь убедиться что completed уже выставлен в новое значение (в коллекции уже актуальный  item, ведь ты оттуда и берешь данные)
а когда тут будет коннект с бэком, с этим кодом у тебя будет два запроса отправляться на обновление

2021-10-08 12:36 UTC, kullias commented on sources/views/activities.js
> +	const button = popup.queryView({localId: "button_add"});
лезть к внутренним виджетам какого-то модуля не очень хорошо
вот потому в том числе этой функции стоит быть методом класса с попапом, чтобы он сам со своим UI разбирался и весь окружающий мир не знал о том, что там у него лежит внутри

2021-10-08 12:36 UTC, kullias commented on sources/views/activities/popup.js
> +			typeId: val => !!val,
или  можно использовать встроенный isNotEmpty https://docs.webix.com/api__rules_isnotempty.html

2021-10-11 07:50 UTC, VeraOrekhXB requested changes

2021-10-11 07:50 UTC, VeraOrekhXB commented on index.html
> +		<link rel="stylesheet" type="text/css" href="//cdn.webix.com/edge/webix.css">
Нужно подключить Webix pro

2021-10-11 07:50 UTC, VeraOrekhXB commented on sources/views/contacts/info.js
> +				{view: "label", localId: "StatusID", label: "Status", css: "status", width: w}
Статус неверно отображается
![image](https://user-images.githubusercontent.com/91135127/136751324-c7eef816-a86b-4fba-8f0a-24253345566e.png)

2021-10-11 07:50 UTC, VeraOrekhXB commented on sources/views/activities/activityPopup.js
> +					{type: "header", template: "Add activity", borderless: true, css: "popup-header", localId: "header"},
Это должно быть в head, a не в body

2021-10-11 08:34 UTC, kullias commented on index.html
> +		<link rel="stylesheet" type="text/css" href="//cdn.webix.com/edge/webix.css">
edu version 8.4.5 included in dev guide https://files.webix.com/30d/02ccc20525da9c4cf8ed21555aab3b87/webix_8.4.5_edu.zip

2021-10-11 09:38 UTC, kullias requested changes

2021-10-11 09:38 UTC, kullias commented on sources/views/activities.js
> +		this.on(this.app, "onTableActivitiesUpdated", () => {
из-за ожидания этого промиса мы сначала видим сброс фильтрации, потом восстановление, что тоже не очень
я думаю подписаться на событие onStoreUpdated таблицы или коллекции прямо в этом вью и не использовать глобальное событие

2021-10-11 09:38 UTC, kullias commented on sources/views/activities.js
> +				icon: "fas fa-plus-square",
иконка так и не появилась :/ я перебрала все префиксы, что там видела - тот же эффект
это только у меня? (еще 2 иконки из сайд меню исчезли)

2021-10-11 09:38 UTC, kullias commented on sources/views/activities.js
> +						this._activityPopup.showPopup(item);
раз в попапе есть доступ к этой коллекции, тут можно просто айди передавать

2021-10-11 09:38 UTC, kullias commented on sources/views/activities/activityPopup.js
> +							click() {
config() стал очень длинным
я бы вынесла клик хэндлер в метод класса

2021-10-11 09:38 UTC, kullias commented on sources/views/activities/activityPopup.js
> +		this.getRoot().close();
сам уничтожится, не надо)
а если где-то кидает ошибку, то проблема не тут

2021-10-11 09:38 UTC, kullias commented on sources/views/activities/activityPopup.js
> +		const button = popup.queryView({localId: "button_add"});
this.$$

2021-10-11 09:38 UTC, kullias commented on sources/views/contacts.js
> +				{$subview: ContactInfoView}
просто ContactInfoView) так тоже работает, но нет необходимости
с листом аналогично
конструктор сам вызовется джет-кодом

2021-10-11 13:03 UTC, VeraOrekhXB approved these changes

2021-10-11 16:04 UTC, kullias requested changes

2021-10-11 16:04 UTC, kullias commented on sources/views/activities.js
> +		activitiesCollection.data.attachEvent("onStoreUpdated", () => {
из-за того что обработчик события продолжает жить, есть баг
как повторить:
- добавляем активити
- переходим в settings
- возвращаемся
- добавляем активити
- в правом верхнем углу сообщение об ошибке

всегда безопаснее использовать this.on

2021-10-11 16:04 UTC, kullias commented on sources/views/activities/activityPopup.js
> +							click: this.buttonAddClick
() => и не придется использовать $scope и webix.$$
но это некритично, в принципе

2021-10-11 16:04 UTC, kullias commented on sources/views/activities/activityPopup.js
>  			webix.$$("popup_form").setValues(formatted);
this.$$
это ж локальная айдишка
webix.$$ конечно работает, но зачем?

2021-10-11 16:07 UTC, kullias commented on sources/views/activities.js
> +		activitiesCollection.data.attachEvent("onStoreUpdated", () => {
альтернатива - чистить обработчик в destroy()

2021-10-11 16:24 UTC, kullias commented on sources/views/activities.js
> +						header: ["Due date", {content: "datepickerFilter", inputConfig: {format: webix.Date.dateToStr(dateFormat)}}],
еще я заметила что не фильтрует. в данных смотришь дату, выбираешь ее в пикере - пусто. даже если время сбрасываешь

2021-10-12 14:27 UTC, kullias approved these changes

2021-10-12 14:46 UTC, kullias approved these changes

2021-10-12 14:50 UTC, merged