Jet Test Application. Stage 3
a-shpak/jet-start-1 pull request #3
Opened 2021-10-20 08:47 UTC by a-shpak

2021-10-20 09:24 UTC, VeraOrekhXB requested changes

2021-10-20 09:24 UTC, VeraOrekhXB commented on sources/locales/en.js
> +	"Edit activity": "Редактирование активности",
Тут должен быть транслейт на английском

2021-10-20 09:24 UTC, VeraOrekhXB commented on sources/locales/en.js
> +	"edit contact": "edit contact",
Лучше придерживаться одного стиля написания свойства в объекте

2021-10-20 09:24 UTC, VeraOrekhXB commented on sources/views/activities.js
> +		function addDays(date, days) {
Лучше вынести в отдельный метод

2021-10-20 09:24 UTC, VeraOrekhXB commented on sources/views/activities.js
> +		const _ = this.$scope.app.getService("locale")._;
Можно в конструкторе добавить свойство ```_```, чтобы в разных методах его не получать каждый раз
А чтобы в каждой JetView не добавлять конструктор, можно создать класс, например, BaseView, который будет экстендится от JetView и в конструкторе которого ты добавишь свойство ```_```. А все твои вьюшки можешь уже экстендить от BaseView

2021-10-20 09:24 UTC, VeraOrekhXB commented on sources/views/activities.js
> +					return obj.State === "Open" && date.getTime() < todayDateTime;
Лучше строку "Open" вынести в константы хотя бы класса (и заодно "Close" тоже можно). Но если используется и в других классах, тогда можно создать глобальную. И ещё не обязательно создавать отдельную константу для каждого значения: можно создать объект, который будет содержать вне нужные состояния статуса

2021-10-20 09:24 UTC, VeraOrekhXB commented on sources/views/contacts/list.js
> +		this.$$("search").attachEvent("onTimedKeyPress", () => {
Лучше аттачить ивент через this.on

2021-10-20 09:24 UTC, VeraOrekhXB commented on sources/views/settings.js
> +			const ui = {
Конфиг получается довольно большой. Было бы лучше создать, например, два метода: один возвращает конфиг для language, второй - для tables

2021-10-20 10:19 UTC, kullias requested changes

2021-10-20 10:19 UTC, kullias commented on sources/views/activities.js
> +			case _("Overdue"):
я бы не полагалась на строки с локалями как на айди
во-первых лишние вызовы "переводчика", во-вторых, отвалятся локали - отвалится и это все
думаю лучше сделать в опциях объекты с id (независимыми от локалей) и value (от тут уже локализация)

2021-10-20 10:19 UTC, kullias commented on sources/views/contacts/list.js
> +					if (!id) return;
а в каких случаях нету айди?

2021-10-20 10:19 UTC, kullias commented on sources/views/contacts/list.js
> +				contactsCollection.filter(() => true);
просто filter()

2021-10-20 10:19 UTC, kullias commented on sources/views/settings.js
> +					{id: "en", value: _("English")},
из любви к юзеру как раз эти лейблы стоит оставлять на языке, о котором они говорят (в этом случае English, Русский)
это для юзера удобнее, если из всех перечисленных он знает только 1, и это не текущий язык, а к примеру китайский
если представить что все опции написаны на китайском, а ты его не знаешь, есть шанс перекликать их все, пока найдешь свой (или придется воспользоваться гугл переводом для страницы)

2021-10-20 10:19 UTC, kullias commented on sources/views/contacts/list.js
> +			const value = this.$$("search").getValue().toLowerCase();
можно еще .trim() добавить (защитит от висячих пробелов)

2021-10-20 10:19 UTC, kullias commented on sources/views/contacts/list.js
> +			if (!item) {
если это проверка на пустые данные, то мб лучше contactsCollection.count() использовать и просто выходить из этой функции?

2021-10-20 10:19 UTC, kullias commented on sources/locales/ru.js
> +};
![Selection_999(315)](https://user-images.githubusercontent.com/31205423/138072080-e606e801-4efb-450e-9eb7-095147ef4421.png)

2021-10-20 10:19 UTC, kullias commented on sources/views/settings/table.js
> +						webix.message({type: "error", text: `${editor.column} must not be empty`});
поскольку таблицы у тебя в мальтивью, если пользователь не заполнил какое-то поле, а потом переключился на другую таблицу, этот попап продолжает появляться
стоит при закрытии таблицы закрыть и эдитор уже

2021-10-20 10:19 UTC, kullias commented on sources/views/activities.js
> +				onAfterTabClick: this.onAfterFilterTabClick
лучше onChange, он срабатывает только по смене активного таба, а не на каждый клик по табу

2021-10-20 10:19 UTC, kullias commented on sources/myapp.js
> +		app.use(plugins.Locale, {storage: webix.storage.local});
![Selection_999(316)](https://user-images.githubusercontent.com/31205423/138073575-068dade5-808d-4b28-8e9d-7477637e8ddf.png)
еще стоит добавить вебиксовые локали
```
webix: {
  en:"en-US",		
  // ...other locales	
}
```

2021-10-20 10:19 UTC, kullias commented on sources/views/contacts/list.js
> +		this.$$("search").attachEvent("onTimedKeyPress", () => {
this.on стоит в джете использовать для событий,чтобы они сами удалялись с окончанием жизни вью

2021-10-20 10:19 UTC, kullias commented on sources/views/contacts/list.js
> +			list.filter(obj => keys.some(key => obj[key].toString().toLowerCase().indexOf(value) !== -1));
код делает вид, что фильтрует по всем полям кроме Photo, но это не так
поскольку по required в ТЗ фильтрация только по некоторым текстовым полям, только их и стоит оставить
сейчас ситуация такая, что статусы фильтруются по их айди как строки. с точки зрения юзера это неправильно и непонятно (например во всех данных может не быть 4 прям точно, а вводит 4 - и ему показывает всех юзеров со статусом по айди 4, но юзер-то четверки этой никогда не увидит в данных)
по минимальному ТЗ стоит включить только те поля, для которых этот код работает правильно 
если есть время и желание, стоит добавить сюда правильную фильтрацию по статусам (по имени статуса) и если очень хочется - по датам (хотя бы по году и может даже с =, > и <)

2021-10-20 10:25 UTC, kullias commented on sources/views/contacts/list.js
> +		this.$$("search").attachEvent("onTimedKeyPress", () => {
потому что чревато багами в ситуации, когда вью закончило свою жизнь, а обработчик еще живет

2021-10-20 10:27 UTC, kullias commented on sources/locales/en.js
> +	"edit contact": "edit contact",
линт не даст

2021-10-20 12:12 UTC, a-shpak commented on sources/locales/en.js
> +	"edit contact": "edit contact",
ага, иначе он ругается

2021-10-20 13:43 UTC, AndreyShpakXB commented on sources/views/contacts/list.js
> +					if (!id) return;
это я пытался понять почему отправляется запрос с undefined, сейчас уже не нужна эта проверка, можно убрать

2021-10-20 18:25 UTC, a-shpak commented on sources/views/contacts/list.js
> +				contactsCollection.filter(() => true);
Так не хочет работать. Мне нужно было очистить фильтр, т.е. чтобы отобразилось всё.

2021-10-21 09:46 UTC, kullias commented on sources/views/contacts/list.js
> +				contactsCollection.filter(() => true);
само по себе работает https://snippet.webix.com/qsb9sn9y
если тут не работает, значит дело в чем-то другом

2021-10-21 10:46 UTC, kullias commented on sources/views/activities/table.js
> +		if (lang === "en") {
в конфиге плагина можно было передать webix:{ ... }
я ж там написала :)
https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/plugins#combining-with-webix-locales
как ты написал - примерно то же делает джет сам, если ему такой объект передать

2021-10-21 10:55 UTC, kullias commented on sources/views/activities.js
> +	}
я тут еще одну вещь заметила:
- выбрать какой-то таб не первый (например завершенные)
- добавить новое незавершенное дело или анчекнуть что-то из завершенных
- в итоге стоит перефильтровать, а то неправильные данные до следующего клика по другому табу

2021-10-21 10:57 UTC, kullias commented on sources/views/activities.js
> +			case "overdue":
после добавления новой активити без заполнения даты клик по этой опции кидает ошибку

activities.js:66 Uncaught TypeError: date.getTime is not a function

2021-10-21 12:49 UTC, AndreyShpakXB commented on sources/views/activities/table.js
> +		if (lang === "en") {
я не мог понять куда пихать этот объект webix:{...}, но теперь разобрался, спасибо

2021-10-21 12:55 UTC, a-shpak commented on sources/views/contacts/list.js
> +				contactsCollection.filter(() => true);
разобрался, нужно было фильтровать список, а не коллекцию

2021-10-22 10:19 UTC, kullias commented on sources/views/activities.js
> +		this.on(this.app, "onActivitiesCollectionUpdated", () => {
в принципе можно было бы положиться и на onStoreUpdated , я думаю
на mode add и update

2021-10-22 10:25 UTC, VeraOrekhXB requested changes

2021-10-22 10:25 UTC, VeraOrekhXB commented on sources/views/settings/table.js
> +				{id: "Value", header: this._("Value"), maxWidth: 300, editor: "text"},
Если начать редактировать ячейку, удалить строку (т.е. оставить пустое значение), то editor остаётся пустым, никак не закрывается. И можно открыть несколько editor'ов в таблице
![image](https://user-images.githubusercontent.com/91135127/138437702-9a836e46-813a-431e-9bec-6919857c27fe.png)

2021-10-22 10:25 UTC, VeraOrekhXB commented on sources/views/activities/table.js
> +export default class ActivitiesTableView extends BaseView {
Вылетела ошибка в консоли
![image](https://user-images.githubusercontent.com/91135127/138438082-26a891d6-6b05-4f1c-9636-6248301c3261.png)

2021-10-22 10:25 UTC, VeraOrekhXB commented on sources/views/activities.js
>  			click: () => this._activityPopup.showPopup()
Вот такая ситуация
![image](https://user-images.githubusercontent.com/91135127/138438376-ca3e790f-e64c-44f6-bfad-cbd1b8c531fb.png)
При добавлении новой activity(дата 2 сентября, все поля были заполнены, кроме времени) появилась ошибка в консоли
![image](https://user-images.githubusercontent.com/91135127/138438471-1c153d3f-6773-47e9-a7f3-029e586b37d5.png)

2021-10-25 07:28 UTC, VeraOrekhXB requested changes

2021-10-25 07:28 UTC, VeraOrekhXB commented on sources/views/contacts/list.js
>  			click: this.onAdd
Нашла небольшой баг
1. Селектишь контакт, у которого есть изображение
2. Нажимаешь кнопку Edit
3. Нажимаешь кнопку Add contact
Все данные в форме очищаются, кроме изображения

2021-10-25 07:53 UTC, VeraOrekhXB approved these changes

2021-10-25 08:42 UTC, kullias approved these changes

2021-10-25 08:42 UTC, kullias commented on sources/views/activities.js
> +				onChange: this.onTabChanged.bind(this)
v => this.onTabChanged(v)

use ES6 :)

2021-10-25 09:01 UTC, merged